### ISSUE TITLE
Constructor of FSampler* API are unavailable on Windows platform

### ISSUE THREAD

**Issue by unknownue** [unknownue/gli-rs#2]
Currently the `new` constructor methods of `FSampler2D`, `FSampler2DArray` ..etc are not successfully compiled on Windows platform.
`FSampler2D`, `FSampler2DArray` ..etc are generic class in original gli library.
MSVC failed to compile function that return generic class with `extern "C"`.

**Comment by Houjuu-Nue** [comment]
If anyone know how to dual with this problem, welcome to comment below.
